################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2023. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-content-assistant-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-content-assistant-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-content-assistant-catalog@sha256:705fadace4f3b7edf02e45630a2eafbaf3fa40ea130b5890ca6844fca8a8f2a6
