################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2023. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-content-assistant-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-content-assistant-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-content-assistant-catalog@sha256:c2149186fcff549fea574c86ab207c60e8f5718a533b2fffbac47347a3a00db8
