###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026 All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: cas.ibm.com/v1
kind: CASCluster
metadata:
  name: casdeploy
  labels:
    app.kubernetes.io/instance: ibm-cas
    app.kubernetes.io/managed-by: ibm-cas
    app.kubernetes.io/name: ibm-cas
    release: 1.0.2
spec:
  ## The version of the Content Assistant operator that is being used.
  appVersion: 1.0.0

  ## MUST exist, used to accept ibm license; valid value only can be "true"
  license:
    accept:

  ##############################################################
  ## Shared configuration for all Content Assistant components #
  ##############################################################
  shared_configuration:
    ## Choose the licensing model for the Content Assistant components.
    ## Valid values are:
    ## "fncm" for IBM FileNet Content Manager,
    sc_cas_license_type: "fncm"

    ## All Content Assistant components must use/share the image_pull_secrets to pull images.
    image_pull_secrets:
      - ibm-entitlement-key

    ## All Content Assistant components must use/share the same docker image repository.  For example, if IBM Entitlement Registry is used, then
    ## it should be "cp.icr.io".  Otherwise, it will be a private registry.
    sc_image_repository: cp.icr.io

    ## All Content Assistant components must use/share the root_ca_secret in order for integration
    root_ca_secret: cas-root-ca

    ## Optional: You can specify a profile size for Content Assistant - valid values are small,medium,large - default is small.
    sc_deployment_profile_size: small

    ## The platform to be deployed specified by the user.  Possible values are: OCP, ROKS, and other.
    sc_deployment_platform: "<Required>"

    ## If the root certificate authority (CA) key of the external service is not signed by the operator root CA key, provide the TLS certificate of
    ## the external service to the component's truststore.
    trusted_certificate_list: [ ]

    ## Provide the storage class name for the file storage provisioner.
    ## Operator will use the provided storage classes to provision required PVC volumes.
    storage_configuration:
      sc_slow_file_storage_classname: "<Required>"

  #############################################
  ######## Vector Database Configuration ######
  #############################################
  vector_database:
    # The type of Vector Database to be used. Currently, only "opensearch" is supported.
    vector_database_type: "opensearch"
    # The secret name that contains the Vector Database credentials.
    vector_database_secret_name: vector-database-secret
    # Vector Database URL which should include host and port. Example https://<VectorDatabaseURL>:9200
    vector_database_url: "<Required>"
    # Vector Database ssl_enabled parameter is used to support database connection over SSL
    vector_database_ssl_enabled: true
    # Secret that contains the Vector Database certificate. Secret should be created with the key tls.crt
    vector_database_certificate: vector-database-certificate-secret
    # Vector Database Authentication type. 2 possible types -  Basic Authentication ( BASICAUTH ) or OIDC
    vector_database_auth_type: BASICAUTH
    ## Vector Database token endpoint required only if OIDC has been selected as the vector database authentication method
    vector_database_oidc_token_endpoint: ""
    ## Vector Database OIDC certificate secret required only if OIDC has been selected as the vector database authentication method
    vector_database_oidc_certificate: vector-database-oidc-certificate-secret